import Foundation
import Observation
import SwiftUI

// Runtime in-app localization. Shared conceptually with apps/android/lib/i18n/resources.ts.
// Date/time formatting uses SwiftUI format styles with the injected locale.

enum AppLanguage: String, CaseIterable, Identifiable, Sendable {
    case vi, en, zh, ja, fr

    var id: Self { self }

    var label: String {
        switch self {
        case .vi: "Tiếng Việt"
        case .en: "English"
        case .zh: "中文"
        case .ja: "日本語"
        case .fr: "Français"
        }
    }

    var locale: Locale {
        switch self {
        case .vi: Locale(identifier: "vi")
        case .en: Locale(identifier: "en")
        case .zh: Locale(identifier: "zh-Hans")
        case .ja: Locale(identifier: "ja")
        case .fr: Locale(identifier: "fr")
        }
    }

    static func fromDevice() -> AppLanguage {
        let code = Locale.preferredLanguages.first?.lowercased() ?? "en"
        if code.hasPrefix("vi") { return .vi }
        if code.hasPrefix("zh") { return .zh }
        if code.hasPrefix("ja") { return .ja }
        if code.hasPrefix("fr") { return .fr }
        return .en
    }
}

@MainActor
@Observable
final class Localizer {
    private static let storageKey = "app_language"

    var language: AppLanguage {
        didSet { UserDefaults.standard.set(language.rawValue, forKey: Self.storageKey) }
    }

    init() {
        if let raw = UserDefaults.standard.string(forKey: Self.storageKey),
           let stored = AppLanguage(rawValue: raw) {
            language = stored
        } else {
            language = .fromDevice()
        }
    }

    func t(_ key: String) -> String {
        Strings.table[language]?[key] ?? Strings.table[.en]?[key] ?? key
    }
}

enum Strings {
    static let table: [AppLanguage: [String: String]] = [
        .en: [
            "app.tagline": "AI short-video studio",
            "splash.tagline": "URL → video in minutes",
            "splash.loading": "Preparing your studio",
            "nav.create": "Create",
            "nav.library": "Library",
            "nav.libraryHeader": "My Videos",
            "nav.settings": "Settings",
            "nav.pipeline": "Pipeline",
            "nav.preview": "Preview",
            "source.url": "URL",
            "source.text": "Text",
            "source.markdown": "Markdown",
            "create.chooseSource": "Choose source",
            "create.menuNews": "News article",
            "create.menuPlain": "Plain text",
            "create.menuMarkdown": "Markdown",
            "create.sourcePicker": "Source",
            "create.heroTitle": "Paste anything.\nTurn it into a video.",
            "create.heroBody": "Start from an article, GitHub repo, text, or Markdown. The pipeline writes, voices, animates, mixes, and renders a vertical short.",
            "create.placeholderUrl": "https://example.com/article",
            "create.placeholderText": "Paste an article, idea, or script",
            "create.placeholderMarkdown": "Paste Markdown content",
            "create.ctaGenerate": "Generate Video",
            "create.recentProjects": "Recent Projects",
            "create.seeAll": "See all",
            "create.emptyTitle": "No videos yet",
            "create.emptyBody": "Paste a source above to create your first rendered short.",
            "library.emptyTitle": "No rendered videos",
            "library.emptyBody": "Create a video first. Completed renders will appear here.",
            "settings.appearance": "Appearance",
            "settings.language": "Language",
            "settings.defaultProduction": "Default production",
            "settings.pipeline": "Pipeline",
            "settings.about": "About",
            "settings.videoTheme": "Video theme",
            "settings.voice": "Voice",
            "settings.autoplay": "Autoplay previews",
            "settings.format": "Format",
            "settings.frameRate": "Frame rate",
            "settings.backend": "Backend",
            "settings.configured": "Configured",
            "settings.notConfigured": "Not configured",
            "settings.aboutTagline": "Frontend concept build",
            "settings.themeDarkNeon": "Dark Neon",
            "settings.themeLightPro": "Light Pro",
            "appearance.system": "System",
            "appearance.light": "Light",
            "appearance.dark": "Dark",
            "generate.creatingTitle": "Creating your video",
            "generate.completeTitle": "Generation complete",
            "generate.creatingSubtitle": "The pipeline is working through each production stage.",
            "generate.completeSubtitle": "Your preview is ready to review.",
            "generate.readyTitle": "Ready to generate",
            "generate.readySubtitle": "Waiting for a source to begin generation.",
            "generate.stoppedSubtitle": "The pipeline stopped before a video was completed.",
            "generate.stopped": "Generation stopped",
            "generate.tryAgain": "Try Again",
            "generate.reviewVideo": "Review Video",
            "preview.mockupTagline": "A BRIGHTER STORY IN 60 SECONDS",
            "preview.renderedMp4": "Rendered MP4",
            "preview.scenes": "Scenes",
            "preview.exportMp4": "Export MP4",
            "preview.unavailableTitle": "Video unavailable",
            "preview.unavailableBody": "This project does not have a rendered MP4 URL.",
            "preview.theme": "Theme",
            "preview.serverDefault": "Server default",
            "preview.voice": "Voice",
            "scene.hook": "Hook",
            "scene.keyPoint": "Key point",
            "scene.outro": "Outro",
            "step.scriptTitle": "Script",
            "step.scriptDetail": "Writing the short-form narrative",
            "step.voiceTitle": "Voice",
            "step.voiceDetail": "Generating natural narration",
            "step.motionTitle": "Motion",
            "step.motionDetail": "Building vertical motion scenes",
            "step.audioMixTitle": "Audio Mix",
            "step.audioMixDetail": "Balancing voice, music, and SFX",
            "step.renderTitle": "Render",
            "step.renderDetail": "Exporting the 9:16 MP4",
            "status.draft": "Draft",
            "status.processing": "Processing",
            "status.completed": "Completed",
            "common.rendered": "Rendered",
        ],
        .vi: [
            "app.tagline": "Xưởng video ngắn AI",
            "splash.tagline": "URL → video trong vài phút",
            "splash.loading": "Đang chuẩn bị xưởng của bạn",
            "nav.create": "Tạo",
            "nav.library": "Thư viện",
            "nav.libraryHeader": "Video của tôi",
            "nav.settings": "Cài đặt",
            "nav.pipeline": "Tiến trình",
            "nav.preview": "Xem trước",
            "source.url": "URL",
            "source.text": "Văn bản",
            "source.markdown": "Markdown",
            "create.chooseSource": "Chọn nguồn",
            "create.menuNews": "Bài báo",
            "create.menuPlain": "Văn bản",
            "create.menuMarkdown": "Markdown",
            "create.sourcePicker": "Nguồn",
            "create.heroTitle": "Dán bất cứ thứ gì.\nBiến thành video.",
            "create.heroBody": "Bắt đầu từ bài báo, repo GitHub, văn bản hay Markdown. Hệ thống tự viết kịch bản, lồng tiếng, tạo chuyển động, trộn âm thanh và render video dọc.",
            "create.placeholderUrl": "https://example.com/bai-viet",
            "create.placeholderText": "Dán bài viết, ý tưởng hoặc kịch bản",
            "create.placeholderMarkdown": "Dán nội dung Markdown",
            "create.ctaGenerate": "Tạo video",
            "create.recentProjects": "Dự án gần đây",
            "create.seeAll": "Xem tất cả",
            "create.emptyTitle": "Chưa có video",
            "create.emptyBody": "Dán nguồn ở trên để tạo video đầu tiên của bạn.",
            "library.emptyTitle": "Chưa có video nào",
            "library.emptyBody": "Hãy tạo video trước. Video hoàn tất sẽ hiện ở đây.",
            "settings.appearance": "Giao diện",
            "settings.language": "Ngôn ngữ",
            "settings.defaultProduction": "Thiết lập mặc định",
            "settings.pipeline": "Tiến trình",
            "settings.about": "Giới thiệu",
            "settings.videoTheme": "Chủ đề video",
            "settings.voice": "Giọng đọc",
            "settings.autoplay": "Tự động phát bản xem trước",
            "settings.format": "Định dạng",
            "settings.frameRate": "Tốc độ khung hình",
            "settings.backend": "Máy chủ",
            "settings.configured": "Đã cấu hình",
            "settings.notConfigured": "Chưa cấu hình",
            "settings.aboutTagline": "Bản dựng ý tưởng giao diện",
            "settings.themeDarkNeon": "Neon tối",
            "settings.themeLightPro": "Sáng Pro",
            "appearance.system": "Hệ thống",
            "appearance.light": "Sáng",
            "appearance.dark": "Tối",
            "generate.creatingTitle": "Đang tạo video",
            "generate.completeTitle": "Đã tạo xong",
            "generate.creatingSubtitle": "Hệ thống đang xử lý từng công đoạn sản xuất.",
            "generate.completeSubtitle": "Bản xem trước đã sẵn sàng.",
            "generate.readyTitle": "Sẵn sàng tạo",
            "generate.readySubtitle": "Đang chờ nguồn để bắt đầu tạo.",
            "generate.stoppedSubtitle": "Tiến trình đã dừng trước khi hoàn tất video.",
            "generate.stopped": "Đã dừng tạo",
            "generate.tryAgain": "Thử lại",
            "generate.reviewVideo": "Xem video",
            "preview.mockupTagline": "CÂU CHUYỆN TRONG 60 GIÂY",
            "preview.renderedMp4": "MP4 đã render",
            "preview.scenes": "Cảnh",
            "preview.exportMp4": "Xuất MP4",
            "preview.unavailableTitle": "Video không khả dụng",
            "preview.unavailableBody": "Dự án này chưa có đường dẫn MP4.",
            "preview.theme": "Chủ đề",
            "preview.serverDefault": "Mặc định máy chủ",
            "preview.voice": "Giọng đọc",
            "scene.hook": "Mở đầu",
            "scene.keyPoint": "Ý chính",
            "scene.outro": "Kết",
            "step.scriptTitle": "Kịch bản",
            "step.scriptDetail": "Viết nội dung dạng ngắn",
            "step.voiceTitle": "Giọng đọc",
            "step.voiceDetail": "Tạo giọng đọc tự nhiên",
            "step.motionTitle": "Chuyển động",
            "step.motionDetail": "Dựng cảnh chuyển động dọc",
            "step.audioMixTitle": "Trộn âm",
            "step.audioMixDetail": "Cân bằng giọng, nhạc và hiệu ứng",
            "step.renderTitle": "Render",
            "step.renderDetail": "Xuất MP4 tỉ lệ 9:16",
            "status.draft": "Nháp",
            "status.processing": "Đang xử lý",
            "status.completed": "Hoàn tất",
            "common.rendered": "Đã render",
        ],
        .zh: [
            "app.tagline": "AI 短视频工作室",
            "splash.tagline": "URL → 几分钟出视频",
            "splash.loading": "正在准备你的工作室",
            "nav.create": "创建",
            "nav.library": "媒体库",
            "nav.libraryHeader": "我的视频",
            "nav.settings": "设置",
            "nav.pipeline": "流水线",
            "nav.preview": "预览",
            "source.url": "URL",
            "source.text": "文本",
            "source.markdown": "Markdown",
            "create.chooseSource": "选择来源",
            "create.menuNews": "新闻文章",
            "create.menuPlain": "纯文本",
            "create.menuMarkdown": "Markdown",
            "create.sourcePicker": "来源",
            "create.heroTitle": "粘贴任何内容。\n一键变成视频。",
            "create.heroBody": "从文章、GitHub 仓库、文本或 Markdown 开始。流水线会自动撰写文案、配音、制作动画、混音并渲染竖版短视频。",
            "create.placeholderUrl": "https://example.com/article",
            "create.placeholderText": "粘贴文章、想法或脚本",
            "create.placeholderMarkdown": "粘贴 Markdown 内容",
            "create.ctaGenerate": "生成视频",
            "create.recentProjects": "最近的项目",
            "create.seeAll": "查看全部",
            "create.emptyTitle": "还没有视频",
            "create.emptyBody": "在上方粘贴素材，创建你的第一个短视频。",
            "library.emptyTitle": "暂无已渲染的视频",
            "library.emptyBody": "请先创建视频。完成渲染后会显示在这里。",
            "settings.appearance": "外观",
            "settings.language": "语言",
            "settings.defaultProduction": "默认制作",
            "settings.pipeline": "流水线",
            "settings.about": "关于",
            "settings.videoTheme": "视频主题",
            "settings.voice": "配音",
            "settings.autoplay": "自动播放预览",
            "settings.format": "格式",
            "settings.frameRate": "帧率",
            "settings.backend": "后端",
            "settings.configured": "已配置",
            "settings.notConfigured": "未配置",
            "settings.aboutTagline": "前端概念版本",
            "settings.themeDarkNeon": "暗黑霓虹",
            "settings.themeLightPro": "亮色专业",
            "appearance.system": "跟随系统",
            "appearance.light": "浅色",
            "appearance.dark": "深色",
            "generate.creatingTitle": "正在生成视频",
            "generate.completeTitle": "生成完成",
            "generate.creatingSubtitle": "流水线正在完成每个制作阶段。",
            "generate.completeSubtitle": "预览已准备就绪。",
            "generate.readyTitle": "准备生成",
            "generate.readySubtitle": "等待素材以开始生成。",
            "generate.stoppedSubtitle": "流水线在生成完成前已停止。",
            "generate.stopped": "生成已停止",
            "generate.tryAgain": "重试",
            "generate.reviewVideo": "查看视频",
            "preview.mockupTagline": "60 秒讲清一个故事",
            "preview.renderedMp4": "已渲染 MP4",
            "preview.scenes": "场景",
            "preview.exportMp4": "导出 MP4",
            "preview.unavailableTitle": "视频不可用",
            "preview.unavailableBody": "此项目没有已渲染的 MP4 链接。",
            "preview.theme": "主题",
            "preview.serverDefault": "服务器默认",
            "preview.voice": "配音",
            "scene.hook": "开场",
            "scene.keyPoint": "要点",
            "scene.outro": "结尾",
            "step.scriptTitle": "脚本",
            "step.scriptDetail": "撰写短视频文案",
            "step.voiceTitle": "配音",
            "step.voiceDetail": "生成自然旁白",
            "step.motionTitle": "动效",
            "step.motionDetail": "构建竖版动效场景",
            "step.audioMixTitle": "混音",
            "step.audioMixDetail": "平衡人声、音乐和音效",
            "step.renderTitle": "渲染",
            "step.renderDetail": "导出 9:16 MP4",
            "status.draft": "草稿",
            "status.processing": "处理中",
            "status.completed": "已完成",
            "common.rendered": "已渲染",
        ],
        .ja: [
            "app.tagline": "AI ショート動画スタジオ",
            "splash.tagline": "URL → 数分で動画に",
            "splash.loading": "スタジオを準備中",
            "nav.create": "作成",
            "nav.library": "ライブラリ",
            "nav.libraryHeader": "マイビデオ",
            "nav.settings": "設定",
            "nav.pipeline": "パイプライン",
            "nav.preview": "プレビュー",
            "source.url": "URL",
            "source.text": "テキスト",
            "source.markdown": "Markdown",
            "create.chooseSource": "ソースを選択",
            "create.menuNews": "ニュース記事",
            "create.menuPlain": "プレーンテキスト",
            "create.menuMarkdown": "Markdown",
            "create.sourcePicker": "ソース",
            "create.heroTitle": "何でも貼り付け。\n動画に変えよう。",
            "create.heroBody": "記事、GitHub リポジトリ、テキスト、Markdown から始めましょう。パイプラインが台本作成、音声、アニメーション、ミックス、縦型動画の書き出しまで自動で行います。",
            "create.placeholderUrl": "https://example.com/article",
            "create.placeholderText": "記事・アイデア・台本を貼り付け",
            "create.placeholderMarkdown": "Markdown を貼り付け",
            "create.ctaGenerate": "動画を生成",
            "create.recentProjects": "最近のプロジェクト",
            "create.seeAll": "すべて表示",
            "create.emptyTitle": "動画がありません",
            "create.emptyBody": "上にソースを貼り付けて最初のショート動画を作成しましょう。",
            "library.emptyTitle": "書き出した動画がありません",
            "library.emptyBody": "まず動画を作成してください。完成した動画がここに表示されます。",
            "settings.appearance": "外観",
            "settings.language": "言語",
            "settings.defaultProduction": "既定の制作設定",
            "settings.pipeline": "パイプライン",
            "settings.about": "情報",
            "settings.videoTheme": "動画テーマ",
            "settings.voice": "音声",
            "settings.autoplay": "プレビューを自動再生",
            "settings.format": "フォーマット",
            "settings.frameRate": "フレームレート",
            "settings.backend": "バックエンド",
            "settings.configured": "設定済み",
            "settings.notConfigured": "未設定",
            "settings.aboutTagline": "フロントエンド コンセプト版",
            "settings.themeDarkNeon": "ダークネオン",
            "settings.themeLightPro": "ライトプロ",
            "appearance.system": "システム",
            "appearance.light": "ライト",
            "appearance.dark": "ダーク",
            "generate.creatingTitle": "動画を作成中",
            "generate.completeTitle": "生成完了",
            "generate.creatingSubtitle": "パイプラインが各制作工程を処理しています。",
            "generate.completeSubtitle": "プレビューの準備ができました。",
            "generate.readyTitle": "生成の準備完了",
            "generate.readySubtitle": "生成を開始するソースを待っています。",
            "generate.stoppedSubtitle": "動画が完成する前にパイプラインが停止しました。",
            "generate.stopped": "生成が停止しました",
            "generate.tryAgain": "再試行",
            "generate.reviewVideo": "動画を確認",
            "preview.mockupTagline": "60秒でわかるストーリー",
            "preview.renderedMp4": "書き出し済み MP4",
            "preview.scenes": "シーン",
            "preview.exportMp4": "MP4 を書き出す",
            "preview.unavailableTitle": "動画は利用できません",
            "preview.unavailableBody": "このプロジェクトには書き出し済みの MP4 URL がありません。",
            "preview.theme": "テーマ",
            "preview.serverDefault": "サーバー既定",
            "preview.voice": "音声",
            "scene.hook": "フック",
            "scene.keyPoint": "要点",
            "scene.outro": "アウトロ",
            "step.scriptTitle": "台本",
            "step.scriptDetail": "ショート向けの構成を作成",
            "step.voiceTitle": "音声",
            "step.voiceDetail": "自然なナレーションを生成",
            "step.motionTitle": "モーション",
            "step.motionDetail": "縦型モーションシーンを構築",
            "step.audioMixTitle": "音声ミックス",
            "step.audioMixDetail": "音声・音楽・効果音を調整",
            "step.renderTitle": "書き出し",
            "step.renderDetail": "9:16 の MP4 を書き出し",
            "status.draft": "下書き",
            "status.processing": "処理中",
            "status.completed": "完了",
            "common.rendered": "書き出し済み",
        ],
        .fr: [
            "app.tagline": "Studio de vidéos courtes IA",
            "splash.tagline": "URL → vidéo en quelques minutes",
            "splash.loading": "Préparation de votre studio",
            "nav.create": "Créer",
            "nav.library": "Bibliothèque",
            "nav.libraryHeader": "Mes vidéos",
            "nav.settings": "Réglages",
            "nav.pipeline": "Pipeline",
            "nav.preview": "Aperçu",
            "source.url": "URL",
            "source.text": "Texte",
            "source.markdown": "Markdown",
            "create.chooseSource": "Choisir la source",
            "create.menuNews": "Article de presse",
            "create.menuPlain": "Texte brut",
            "create.menuMarkdown": "Markdown",
            "create.sourcePicker": "Source",
            "create.heroTitle": "Collez n'importe quoi.\nTransformez-le en vidéo.",
            "create.heroBody": "Partez d'un article, d'un dépôt GitHub, d'un texte ou de Markdown. Le pipeline rédige, met en voix, anime, mixe et rend une vidéo verticale.",
            "create.placeholderUrl": "https://example.com/article",
            "create.placeholderText": "Collez un article, une idée ou un script",
            "create.placeholderMarkdown": "Collez du contenu Markdown",
            "create.ctaGenerate": "Générer la vidéo",
            "create.recentProjects": "Projets récents",
            "create.seeAll": "Tout voir",
            "create.emptyTitle": "Aucune vidéo",
            "create.emptyBody": "Collez une source ci-dessus pour créer votre première vidéo.",
            "library.emptyTitle": "Aucune vidéo rendue",
            "library.emptyBody": "Créez d'abord une vidéo. Les rendus terminés apparaîtront ici.",
            "settings.appearance": "Apparence",
            "settings.language": "Langue",
            "settings.defaultProduction": "Production par défaut",
            "settings.pipeline": "Pipeline",
            "settings.about": "À propos",
            "settings.videoTheme": "Thème vidéo",
            "settings.voice": "Voix",
            "settings.autoplay": "Lecture auto des aperçus",
            "settings.format": "Format",
            "settings.frameRate": "Fréquence d'images",
            "settings.backend": "Backend",
            "settings.configured": "Configuré",
            "settings.notConfigured": "Non configuré",
            "settings.aboutTagline": "Version concept front-end",
            "settings.themeDarkNeon": "Néon sombre",
            "settings.themeLightPro": "Clair Pro",
            "appearance.system": "Système",
            "appearance.light": "Clair",
            "appearance.dark": "Sombre",
            "generate.creatingTitle": "Création de votre vidéo",
            "generate.completeTitle": "Génération terminée",
            "generate.creatingSubtitle": "Le pipeline traite chaque étape de production.",
            "generate.completeSubtitle": "Votre aperçu est prêt.",
            "generate.readyTitle": "Prêt à générer",
            "generate.readySubtitle": "En attente d'une source pour lancer la génération.",
            "generate.stoppedSubtitle": "Le pipeline s'est arrêté avant la fin de la vidéo.",
            "generate.stopped": "Génération arrêtée",
            "generate.tryAgain": "Réessayer",
            "generate.reviewVideo": "Voir la vidéo",
            "preview.mockupTagline": "UNE HISTOIRE EN 60 SECONDES",
            "preview.renderedMp4": "MP4 rendu",
            "preview.scenes": "Scènes",
            "preview.exportMp4": "Exporter en MP4",
            "preview.unavailableTitle": "Vidéo indisponible",
            "preview.unavailableBody": "Ce projet n'a pas d'URL MP4 rendue.",
            "preview.theme": "Thème",
            "preview.serverDefault": "Valeur serveur par défaut",
            "preview.voice": "Voix",
            "scene.hook": "Accroche",
            "scene.keyPoint": "Point clé",
            "scene.outro": "Conclusion",
            "step.scriptTitle": "Script",
            "step.scriptDetail": "Rédaction du récit court",
            "step.voiceTitle": "Voix",
            "step.voiceDetail": "Génération d'une narration naturelle",
            "step.motionTitle": "Animation",
            "step.motionDetail": "Création des scènes animées verticales",
            "step.audioMixTitle": "Mixage audio",
            "step.audioMixDetail": "Équilibrage voix, musique et effets",
            "step.renderTitle": "Rendu",
            "step.renderDetail": "Export du MP4 9:16",
            "status.draft": "Brouillon",
            "status.processing": "En cours",
            "status.completed": "Terminé",
            "common.rendered": "Rendu",
        ],
    ]
}

// Video-theme + appearance option enums used by Settings pickers.
enum AppearanceMode: String, CaseIterable, Identifiable {
    case system, light, dark
    var id: Self { self }

    var colorScheme: ColorScheme? {
        switch self {
        case .system: nil
        case .light: .light
        case .dark: .dark
        }
    }

    var labelKey: String {
        switch self {
        case .system: "appearance.system"
        case .light: "appearance.light"
        case .dark: "appearance.dark"
        }
    }
}
